LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE =
LOCAL_MODULE = mediatek-framework
LOCAL_MODULE_CLASS = JAVA_LIBRARIES
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .jar
LOCAL_SRC_FILES = mediatek-framework.jar
LOCAL_CERTIFICATE := platform
LOCAL_DEX_PREOPT := true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE =
LOCAL_MODULE = mediatek-common
LOCAL_MODULE_CLASS = JAVA_LIBRARIES
LOCAL_MODULE_PATH =
LOCAL_MODULE_RELATIVE_PATH =
LOCAL_MODULE_SUFFIX = .jar
LOCAL_DEX_PREOPT := true
LOCAL_SRC_FILES = mediatek-common.jar
LOCAL_CERTIFICATE := platform
include $(BUILD_PREBUILT)
